---
- hosts: all
  become: true

  tasks:
    - name: List mounted devices on hosts
      shell: cat /etc/fstab
      register: fstab
      tags:
        - never
        - discover
  
    - name: Print mounted devices on hosts
      debug: 
        msg: "{{ fstab.stdout + fstab.stderr }} " 
      tags:
        - never
        - discover
  
    - name: Install tools to set quotas
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'quota', 'linux-image-extra-virtual' ]

    - name: Reboot the machine
      reboot:

    - name: Mount up device with quota
      mount:
        path: "{{ quota_device_path }}"
        src: "{{ quota_device_name }}"
        opts: usrquota,grpquota
        fstype: ext4
        state: present

    - name: Remount disk
      mount:
        path: "{{ quota_device_path }}"
        state: remounted

    - stat:
          path: "{{ quota_device_path }}/aquota.user"
      register: quota

    - name: Enable quotas
      shell: |
        quotacheck -ugm {{ quota_device_path }}
        quotaon -v {{ quota_device_path }}
      when: quota.stat.exists == False
